### ISSUE TITLE
Which markets does it suport?

### ISSUE THREAD

**Issue by Marcin-DarkSpaceStudio** [toddwschneider/stocks#5]
for such a question but I couldn't find it on IEX API page. Does this support EU markets? And if yes, what is the syntax?

**Comment by toddwschneider** [comment]
I believe it is only US markets. See here for the list of supported symbols: https://iextrading.com/trading/eligible-symbols/

Also this GitHub issue is maybe relevant: https://github.com/iexg/IEX-API/issues/76

**Comment by sjorsvanheuveln** [comment]
Have European markets been included by now? I would like to sign up, but I want to access euronext.

**Comment by toddwschneider** [comment]
@sjorsvanheuveln I think that is a question for IEX Cloud, not this repo. I don't know if they support European markets, but you can find out more on their website: https://iexcloud.io/
